# Generated by Django 5.0.6 on 2024-05-23 15:47

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.fields.StreamField([('footer', wagtail.blocks.StructBlock([]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('subheaders', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('card_title', wagtail.blocks.CharBlock(max_length=10000, required=False)), ('links', wagtail.blocks.URLBlock(help_text='Please provide Links', required=False))])))]))], blank=True, null=True),
        ),
    ]
