# Generated by Django 5.0.6 on 2024-05-23 15:58

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_footer_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='footer',
            field=wagtail.fields.StreamField([('footer', wagtail.blocks.StructBlock([('rightText', wagtail.blocks.CharBlock(max_length=10000, required=False)), ('leftText', wagtail.blocks.CharBlock(max_length=10000, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=10000, required=False)), ('subheaders', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('card_title', wagtail.blocks.CharBlock(max_length=10000, required=False)), ('links', wagtail.blocks.PageChooserBlock(help_text='Please provide Links', required=False))])))]))], blank=True, null=True),
        ),
    ]
