# Generated by Django 5.0.6 on 2024-05-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_header'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='final_challenge_section_cta_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Final challenge section CTA open in new tab'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_challenge_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Final challenge section image'),
        ),
    ]
