# Generated by Django 5.0.6 on 2024-05-25 14:48

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_final_challenge_section_cta_open_in_new_tab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='final_challenge_section_cta_open_in_new_tab',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='final_challenge_section_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_section',
            field=wagtail.fields.StreamField([('hero_section', wagtail.blocks.StructBlock([('hero_section_title', wagtail.blocks.RichTextBlock(required=False)), ('hero_section_subttitle', wagtail.blocks.TextBlock(default='hi there', max_length=1000)), ('hero_words', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(max_length=100))), ('hero_images', wagtail.blocks.StructBlock([('image_url', wagtail.blocks.URLBlock(required=False)), ('images', wagtail.images.blocks.ImageChooserBlock())]))]))], blank=True, null=True),
        ),
    ]
