# Generated by Django 5.0.6 on 2024-05-25 15:05

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_final_challenge_section_cta_open_in_new_tab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_section',
            field=wagtail.fields.StreamField([('hero_section', wagtail.blocks.StructBlock([('hero_section_title', wagtail.blocks.RichTextBlock(required=False)), ('hero_words', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(max_length=100))), ('hero_image', wagtail.blocks.StructBlock([('image_url', wagtail.blocks.URLBlock(required=False)), ('images', wagtail.images.blocks.ImageChooserBlock())])), ('hero_section_subttitle', wagtail.blocks.TextBlock(default='hi there', max_length=1000)), ('hero_buttons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))), ('hero_images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image_url', wagtail.blocks.URLBlock(required=False)), ('images', wagtail.images.blocks.ImageChooserBlock())])))]))], blank=True, null=True),
        ),
    ]
