# Generated by Django 5.0.6 on 2024-05-25 20:56

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_section',
            field=wagtail.fields.StreamField([('about_section', wagtail.blocks.StructBlock([('about_main_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('about_title', wagtail.blocks.TextBlock(help_text='about title', required=True)), ('about_description', wagtail.blocks.TextBlock(help_text='about description', required=True)), ('pointers_block', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('main_title', wagtail.blocks.TextBlock(required=False)), ('pointers', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(required=True)))])))]))], blank=True, null=True),
        ),
    ]
