# Generated by Django 5.0.6 on 2024-05-26 10:09

import home.models
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_knowledge_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='project_section',
            field=wagtail.fields.StreamField([('project_section', wagtail.blocks.StructBlock([('main_title', wagtail.blocks.TextBlock(required=True)), ('tags', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(required=True))), ('project_subsection', wagtail.blocks.ListBlock(home.models.ProjectSubsection))]))], blank=True, null=True),
        ),
    ]
