# Generated by Django 5.0.6 on 2024-05-26 15:28

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_project_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='achieve_section',
            field=wagtail.fields.StreamField([('achieve_section', wagtail.blocks.StructBlock([('subblocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.TextBlock(required=True)), ('metric', wagtail.blocks.TextBlock(required=True)), ('postfix', wagtail.blocks.BooleanBlock(required=True)), ('prefix', wagtail.blocks.BooleanBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
