# Generated by Django 5.0.6 on 2024-05-26 15:37

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_achieve_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email_section',
            field=wagtail.fields.StreamField([('email_section', wagtail.blocks.StructBlock([('email_section_title', wagtail.blocks.TextBlock(required=True)), ('email_section_desc', wagtail.blocks.TextBlock(required=True)), ('email_images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image_url', wagtail.blocks.URLBlock(required=False)), ('images', wagtail.images.blocks.ImageChooserBlock())])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='achieve_section',
            field=wagtail.fields.StreamField([('achieve_section', wagtail.blocks.StructBlock([('subblocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.TextBlock(required=True)), ('metric', wagtail.blocks.TextBlock(required=True)), ('postfix', wagtail.blocks.BooleanBlock(required=False)), ('prefix', wagtail.blocks.BooleanBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
