# Generated by Django 5.0.6 on 2024-05-26 16:37

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_email_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='achieve_section',
            field=wagtail.fields.StreamField([('achieve_section', wagtail.blocks.StructBlock([('subblocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.IntegerBlock(required=True)), ('metric', wagtail.blocks.TextBlock(required=True)), ('postfix', wagtail.blocks.BooleanBlock(required=False)), ('prefix', wagtail.blocks.BooleanBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
